name: schedule_application
publish_to: 'none'
version: 4.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # architecture
  flutter_state_notifier: ^0.7.0
  rxdart: ^0.27.1

  # local storage
  shared_preferences: ^2.0.6

  # network
  dio: ^4.0.0

  # ui
  cupertino_icons: ^1.0.2
  share_plus: ^2.1.4

  # gen
  freezed_annotation: ^0.14.2

  # util
  enum_to_string: ^2.0.1
  roundcheckbox: ^2.0.2
  url_launcher: ^6.0.8

  # keyboard
  keyboard_actions: "^3.3.1+1"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.3
  flutter_gen_runner: ^3.1.1
  freezed: ^0.14.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
